src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="new_user")
 */
class User implements UserInterface
{
    CONST ROLE_RIP = "ROLE_RIP";
    CONST ROLE_PILOTE = "ROLE_PILOTE";
    CONST ROLE_CHEF_AGENCE = "ROLE_CHEF_AGENCE";
    CONST ROLE_ADMIN = "ROLE_ADMIN";
    CONST ROLES = [
        "RIP" => self::ROLE_RIP,
        "Pilote" => self::ROLE_PILOTE,
        "Chef d'agence" => self::ROLE_CHEF_AGENCE,
        "Administrateur" => self::ROLE_ADMIN
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $nni;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $lastname;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateLastReview;

    /**
     * @ORM\Column(type="decimal", precision=3, scale=2, nullable=false)
     */
    private $coefficient;

    /**
     * @ORM\OneToMany(targetEntity="CommentaireChantier", mappedBy="user")
     */
    private $commentaires;

    /**
     * @ORM\OneToMany(targetEntity="Planning", mappedBy="user")
     */
    private $plannings;

    /**
     * @ORM\OneToMany(targetEntity="Chantier", mappedBy="responsable")
     */
    private $chantiersResponsable;

    /**
     * @ORM\OneToMany(targetEntity="Chantier", mappedBy="preparateur")
     */
    private $chantiersPreparateur;

    /**
     * @ORM\OneToMany(targetEntity="Revue", mappedBy="createdBy")
     */
    private $revues;

    /**
     * @ORM\OneToMany(targetEntity="Revue", mappedBy="createdFor")
     */
    private $revuesCreated;

    /**
     * @ORM\ManyToOne(targetEntity="BO", inversedBy="users")
     */
    private $bo;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Action", mappedBy="createdBy", cascade={"persist"})
     */
    private $actions;

    /**
     * User constructor.
     */
    public function __construct()
    {
        $this->coefficient = 1;
        $this->commentaires = new ArrayCollection();
        $this->chantiersResponsable = new ArrayCollection();
        $this->chantiersPreparateur = new ArrayCollection();
        $this->revues = new ArrayCollection();
        $this->actions = new ArrayCollection();
        $this->plannings = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @see UserInterface
     */
    public function getUsername()
    {
        return $this->firstname . " " . $this->lastname;
    }

    /**
     * @see UserInterface
     */
    public function getRoles()
    {
        return $this->roles;
    }

    public function setRoles(array $roles)
    {
        $this->roles = $roles;
        return $this;
    }

    /**
     * @param string $role
     * @return User
     */
    public function addRole(string $role)
    {
        $role = strtoupper($role);

        if (!in_array($role, $this->roles, true)) {
            $this->roles[] = $role;
        }

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword()
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
        return null;
    }

    /** @see UserInterface */
    public function eraseCredentials() {}

    /**
     * @return mixed
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * @param mixed $firstname
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;
    }

    /**
     * @return mixed
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * @param mixed $lastname
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;
    }

    /**
     * @return mixed
     */
    public function getDateLastReview()
    {
        return $this->dateLastReview;
    }

    /**
     * @param mixed $dateLastReview
     */
    public function setDateLastReview($dateLastReview)
    {
        $this->dateLastReview = $dateLastReview;
    }

    /**
     * @return float
     */
    public function getCoefficient()
    {
        return $this->coefficient;
    }

    /**
     * @param $coefficient
     */
    public function setCoefficient($coefficient)
    {
        $this->coefficient = $coefficient;
    }

    /**
     * @return mixed
     */
    public function getCommentaires()
    {
        return $this->commentaires;
    }

    /**
     * @param mixed $commentaires
     */
    public function setCommentaires($commentaires)
    {
        $this->commentaires = $commentaires;
    }

    /**
     * @param CommentaireChantier $commentaire
     */
    public function addCommentaire(CommentaireChantier $commentaire)
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
        }
    }

    /**
     * @param CommentaireChantier $commentaire
     */
    public function removeCommentaire(CommentaireChantier $commentaire)
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
        }
    }

    /**
     * @return mixed
     */
    public function getChantiersResponsable()
    {
        return $this->chantiersResponsable;
    }

    /**
     * @param mixed $chantiersResponsable
     */
    public function setChantiersResponsable($chantiersResponsable)
    {
        $this->chantiersResponsable = $chantiersResponsable;
    }

    /**
     * @param Chantier $chantier
     */
    public function addChantierResponsable(Chantier $chantier)
    {
        if (!$this->chantiersResponsable->contains($chantier)) {
            $this->chantiersResponsable->add($chantier);
        }
    }

    /**
     * @param Chantier $chantier
     */
    public function removeChantierResponsable(Chantier $chantier)
    {
        if ($this->chantiersResponsable->contains($chantier)) {
            $this->chantiersResponsable->removeElement($chantier);
        }
    }

    /**
     * @return mixed
     */
    public function getChantiersPreparateur()
    {
        return $this->chantiersPreparateur;
    }

    /**
     * @param mixed $chantiersPreparateur
     */
    public function setChantiersPreparateur($chantiersPreparateur)
    {
        $this->chantiersPreparateur = $chantiersPreparateur;
    }

    /**
     * @param Chantier $chantier
     */
    public function addChantierPreparateur(Chantier $chantier)
    {
        if (!$this->chantiersPreparateur->contains($chantier)) {
            $this->chantiersPreparateur->add($chantier);
        }
    }

    /**
     * @param Chantier $chantier
     */
    public function removeChantierPreparateur(Chantier $chantier)
    {
        if ($this->chantiersPreparateur->contains($chantier)) {
            $this->chantiersPreparateur->removeElement($chantier);
        }
    }

    /**
     * @return string
     */
    public function getIdentity()
    {
        return $this->getFirstname() . " " . $this->getLastname();
    }

    /**
     * @return mixed
     */
    public function getBo()
    {
        return $this->bo;
    }

    /**
     * @param mixed $bo
     */
    public function setBo($bo)
    {
        $this->bo = $bo;
    }

    /**
     * @return ArrayCollection
     */
    public function getRevues()
    {
        return $this->revues;
    }

    /**
     * @param ArrayCollection $revues
     */
    public function setRevues(ArrayCollection $revues)
    {
        $this->revues = $revues;
    }

    /**
     * @return mixed
     */
    public function getRevuesCreated()
    {
        return $this->revuesCreated;
    }

    /**
     * @param mixed $revuesCreated
     */
    public function setRevuesCreated($revuesCreated)
    {
        $this->revuesCreated = $revuesCreated;
    }


    /**
     * @return mixed
     */
    public function getActions()
    {
        return $this->actions;
    }

    /**
     * @param mixed $actions
     */
    public function setActions($actions)
    {
        $this->actions = $actions;
    }

    /**
     * @param Action $action
     */
    public function addAction(Action $action)
    {
        $this->actions->add($action);
    }

    /**
     * @param Action $action
     */
    public function removeAction(Action $action)
    {
        $this->actions->removeElement($action);
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->firstname . " " . $this->lastname;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }

    /**
     * @return mixed
     */
    public function getNni()
    {
        return $this->nni;
    }

    /**
     * @param mixed $nni
     */
    public function setNni($nni)
    {
        $this->nni = $nni;
    }

	/**
	 * Retourne le nom complet
	 *
	 * @return string
	 */
    public function getFullName(){
    	return $this->getLastname() . ' ' . $this->getFirstname();
	}

    /**
     * @param string $role
     * @return bool
     */
    public function hasRole(string $role)
    {
        return in_array($role, $this->roles);
    }

    /**

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\BO;
use App\Entity\User;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Choice;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class UserType extends AbstractType
{
    /** @var TranslatorInterface */
    private $translator;

    /**
     * CommuneType constructor.
     * @param TranslatorInterface $translator
     */
    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstname', TextType::class, [
                "label" => $this->translator->trans("user.firstname"),
                "required" => true,
                "attr" => [
                    "class" => "form-control textforms"
                ]
            ])
            ->add('lastname', TextType::class, [
                "label" => $this->translator->trans("user.lastname"),
                "required" => true,
                "attr" => [
                    "class" => "form-control textforms"
                ]
            ])
            ->add('nni', TextType::class, [
                "label" => "NNI",
                "required" => false,
                "attr" => [
                    "class" => "form-control textforms"
                ]
            ])
            ->add('email', EmailType::class, [
                "label" => $this->translator->trans("user.email"),
                "required" => false,
                "attr" => [
                    "class" => "form-control textforms"
                ]
            ])
            ->add('coefficient', NumberType::class, [
                "label" => $this->translator->trans("user.ratio"),
                'html5' => true,
                "required" => true,
                "attr" => [
                    "min" => 0,
                    "scale" => 2,
                    "step" => 0.05,
                    "class" => "form-control textforms",
                    "autocomplete" => "off"
                ]
            ])
            ->add('dateLastReview', DateType::class, [
                "label" => $this->translator->trans("user.date_last_review"),
                "required" => false,
                "format" => "dd/MM/yyyy",
                "widget" => "single_text",
                "attr" => [
                    "class" => "form-control textforms datepicker",
                    "autocomplete" => "off"
                ]
            ])
            ->add('bo', EntityType::class, [
                "label" => $this->translator->trans("bo.libelle"),
                "class" => BO::class,
                "choice_label" => "name",
                "required" => false,
                "multiple" => false,
                "expanded" => false,
                "attr" => [
                    "class" => "form-control textforms select2"
                ]
            ])
            ->add('roles', ChoiceType::class, [
                "label" => $this->translator->trans("user.role", ["%count%" => 1]),
                "required" => true,
                "multiple" => true,
                'choices'  => User::ROLES,
                "attr" => [
                    "class" => "textforms form-control select2"
                ]
            ])
            ->add("submit", SubmitType::class, [
                "label" => $this->translator->trans("utils.validate"),
                "attr" => [
                    "class" => "btn btn-success btn-sm"
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

templates/user/_charges.html.twig
<div class="row">
    <div class="col-md-12 mb-3">
        <a class="btn btn-primary select-time"
           data-start="{{ "now"|date("d/m/Y") }}"
           data-end="{{ "now"|date_modify("+1 month")|date("d/m/Y") }}"
           data-duration="1">
            {{ "utils.calendar.number_month" | trans({"%number%" : 1}) }}
        </a>
        <a class="btn btn-default select-time"
           data-start="{{ "now"|date("d/m/Y") }}"
           data-end="{{ "now"|date_modify("+3 month")|date("d/m/Y") }}"
           data-duration="3">
            {{ "utils.calendar.number_month" | trans({"%number%" : 3}) }}
        </a>
        <a class="btn btn-default select-time"
           data-start="{{ "now"|date("d/m/Y") }}"
           data-end="{{ "now"|date_modify("+6 month")|date("d/m/Y") }}"
           data-duration="6">
            {{ "utils.calendar.number_month" | trans({"%number%" : 6}) }}
        </a>
        <a class="btn btn-default select-time"
           data-start="{{ "now"|date("d/m/Y") }}"
           data-end="{{ "now"|date_modify("+1 year")|date("d/m/Y") }}"
           data-duration="12">
            {{ "utils.calendar.number_month" | trans({"%number%" : 12}) }}
        </a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="datatable table table-striped table-bordered">
            <thead>
            <tr>
                <th class="sorting_asc">Identite</th>
                <th>{{ "user.sites_in_progress" | trans() }}</th>
                <th>{{ "user.time_available" | trans() }} (h)</th>
                <th>{{ "user.total_load" | trans() }} (h)</th>
                <th>{{ "user.percentage_charge" | trans() }} (%)</th>
                {% if "stats" not in app.request.get("_route") %}
                    <th></th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.identity }}</td>
                    <td data-info="open">{{ datas[user.id]["open"]}}</td>
                    <td data-info="dispo">{{ datas[user.id]["dispo"] }}</td>
                    <td data-info="charge">{{ datas[user.id]["charge"] }}</td>
                    <td data-info="pourcentage">
                        {% if datas[user.id]["dispo"] != 0 %}
                            {{ (datas[user.id]["charge"] / datas[user.id]["dispo"] * 100) | round(1, "common") | number_format(1) }}
                        {% else %}
                            0
                        {% endif %}
                    </td>
                    {% if "stats" not in app.request.get("_route") %}
                        <td data-id="{{ user.id }}">
                            <a class="btn btn-xs btn-success select-prepa"><i class="fa fa-check"></i></a>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

templates/user/datatable.html.twig
<div class="row">
    <div class="col-md-12">
        <table class="datatable table table-striped table-bordered">
            <thead>
                <tr>
                    <th class="sorting_asc">{{ "user.identity" | trans() }}</th>
                    <th>{{ "bo.libelle" | trans() }}</th>
                    <th>{{ "user.date_last_review" | trans() }}</th>
                    <th>{{ "site.count" | trans() }}</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td class="redirect" data-href="{{ path("user_info", {"id" : user.id}) }}">{{ user.firstname }} {{ user.lastname }}</td>
                        <td>
                            {% if user.bo %}
                                {{ user.bo.name }}
                            {% endif %}
                        </td>
                        <td>
                            {% if user.dateLastReview %}
                                {{ user.dateLastReview | date("d/m/Y") }}
                            {% endif %}
                        </td>
                        <td>{{ userService.getSites(user) | length() }}</td>
                        <td class="text-center">
                            {% if "review" in app.request.get('_route') %}
                                <a href="{{ path("user_rip_review_sites", {"id" : user.id}) }}"
                                   target="_blank"
                                   class="btn btn-xs btn-warning"
                                   title="{{ "utils.review" | trans() }}">
                                    <i class="fa fa-book"></i>
                                </a>
                            {% endif %}
                            <a href="{{ path("user_info", {"id" : user.id}) }}"
                               class="btn btn-xs btn-primary"
                               title="{{ "utils.visualise" | trans() }}">
                                <i class="fa fa-eye"></i>
                            </a>
                            {% if user.hasRole(constant('App\\Entity\\User::ROLE_RIP')) %}
                                <a href="{{ path("user_stats", {"id" : user.id}) }}"
                                   class="btn btn-xs bg-purple"
                                   title="{{ "user.charge" | trans({"%count%" : 1}) }}">
                                    <i class="fa fa-bar-chart"></i>
                                </a>
                            {% endif %}
                            <a class="btn btn-xs btn-danger bootbox-confirm"
                               data-message="{{ "user.sentence.delete" | trans() }}"
                               data-href="{{ path("user_delete", {"id" : user.id}) }}"
                               data-button="{{ "utils.delete" | trans() }}"
                               data-classes="btn-sm btn-danger"
                               title="{{ "utils.delete" | trans() }}">
                                <i class="fa fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

templates/user/importPlanning.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ "title.import_planning" | trans() }}{% endblock %}

{% block body %}
    <div class="row">
        <div id="FirstBox" class="col-md-12">
            <div class="box box-solid">
                <div class="box-group">
                    <div class="panel box">
                        <div class="box-header with-border">

                            <div class="row">
                                <div class="col-md-6 col-md-offset-3">
                                    {{ form_start(form) }}
                                        <div class="col-md-12 my-3">
                                            {{ form_widget(form.fichier) }}
                                        </div>
                                        <div class="col-md-12 mt-3 text-right">
                                            <span id="Spinner" class="d-none">
                                                <i class="fa fa-spinner fa-spin"></i>
                                            </span>
                                            {{ form_widget(form.submit) }}
                                        </div>
                                    {{ form_end(form) }}
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/info.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ "title.info.user" | trans() }}{% endblock %}

{% block body %}
    <div class="navigation-block">
        <ol class="breadcrumb">
            <li><a href="{{ path("user_main") }}"><i class="fa fa-users"></i> {{ "user.libelle" | trans({"%count%" : 2}) }}</a></li>
            <li class="active">
                {% if "new" not in app.request.get('_route') %}
                    {{ user.firstname }} {{ user.lastname }}
                {% else %}
                    {{ "utils.creating" | trans() }}
                {% endif %}
            </li>
        </ol>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-solid">
                <div class="box-group">
                    <div class="panel box">
                        <div class="box-header with-border">

                            {{ form_start(userForm) }}
                                <div class="row">
                                    <div class="col-md-4">
                                        {{ form_row(userForm.firstname) }}
                                    </div>
                                    <div class="col-md-4">
                                        {{ form_row(userForm.bo) }}
                                    </div>
                                    <div class="col-md-4">
                                        {{ form_row(userForm.dateLastReview) }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        {{ form_row(userForm.lastname) }}
                                    </div>
                                    <div class="col-md-4">
                                        {% if is_granted(constant('App\\Entity\\User::ROLE_RIP')) or is_granted( constant('App\\Entity\\User::ROLE_PILOTE')) %}
                                            <span class="hide">{{ form_row(userForm.nni) }}</span>
                                            <label for="NNI">NNI</label>
                                            <input type="text" id="NNI" class="textforms form-control" value="{{ user.nni }}" disabled>
                                        {% else %}
                                            {{ form_row(userForm.nni) }}
                                        {% endif %}
                                    </div>
                                    <div class="col-md-4">
                                        {% if is_granted(constant('App\\Entity\\User::ROLE_ADMIN')) %}
                                            {{ form_row(userForm.roles) }}
                                        {% else %}
                                            <span class="hide">{{ form_row(userForm.roles) }}</span>
                                            <label for="Roles">{{ "user.role" | trans({'%count%': 2}) }}</label>
                                            <input type="text" id="Roles" class="textforms form-control" value="{{ user.roles | join(', ') }}" disabled>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        {{ form_row(userForm.email) }}
                                    </div>
                                    <div class="col-md-4{% if not is_granted(constant('App\\Entity\\User::ROLE_ADMIN')) %} hide{% endif %}">
                                        {{ form_row(userForm.coefficient) }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 text-right">
                                        {{ form_widget(userForm.submit) }}
                                    </div>
                                </div>
                            {{ form_end(userForm) }}

                            {% if "new" not in app.request.get("_route") %}

                                <hr>
                                {% set lastReview = revueService.getLastyReviewByUser(user) %}
                                {% if lastReview is not null and lastReview.commentaire is not null %}
                                    <p>
                                        <strong>{{ "user.last_commentary_review" | trans() }}</strong> : {{ lastReview.commentaire.message }}
                                    </p>
                                {% endif %}
                                <div class="row">
                                    <div class="col-md-12">
                                        <p>
                                            <strong>{{ "site.info_open" | trans() }}</strong> : {{ userService.getChantiersByStatus(user, true) | length() }}
                                            <br/>
                                            <strong>{{ "site.info_close" | trans() }}</strong> : {{ userService.getChantiersByStatus(user, false) | length() }}
                                        </p>
                                    </div>
                                </div>
                                {% include "chantier/datatable.html.twig" %}

                                <hr>
                                <div class="row">
                                    <div class="col-md-12 text-right">
                                        <a href="{{ path("user_stats", {"id" : user.id}) }}" class="btn bg-purple btn-sm">
                                            <i class="fa fa-bar-chart"></i> {{ "user.charge" | trans({"%count%" : 1}) }}
                                        </a>
                                        <a class="btn btn-primary btn-sm open-logbook"
                                            data-id="{{ user.id }}"
                                            data-type="{{ constant('App\\Entity\\Action::TYPE_USER') }}"
                                            data-object_class="User">
                                            <i class="fa fa-book"></i> {{ "utils.logbook" | trans() }}
                                        </a>
                                        {% if user.hasRole(constant('App\\Entity\\User::ROLE_RIP')) %}
                                            <a href="{{ path("user_rip_review_sites", {"id" : user.id}) }}"
                                               class="btn btn-sm btn-warning"
                                               target="_blank"
                                               title="{{ "utils.review" | trans() }}">
                                                <i class="fa fa-book"></i> {{ "utils.review" | trans() }}
                                            </a>
                                        {% endif %}
                                        <a class="btn btn-sm btn-danger bootbox-confirm"
                                           data-message="{{ "user.sentence.delete" | trans() }}"
                                           data-href="{{ path("user_delete", {"id" : user.id}) }}"
                                           data-button="{{ "utils.delete" | trans() }}"
                                           data-classes="btn-sm btn-danger">
                                            <i class="fa fa-trash"></i> {{ "utils.delete" | trans() }}
                                        </a>
                                    </div>
                                </div>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/main.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ "title.main.user" | trans() }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-solid">
                <div class="box-group">
                    <div class="panel box">
                        <div class="box-header with-border">
                            <div class="row">
                                <div class="col-md-12 text-right">
                                    <a href="{{ path("user_import_planning") }}" class="btn btn-success btn-sm">{{ "user.import_planning" | trans() }}</a>
                                    <a href="{{ path("user_new") }}" class="btn btn-success btn-sm my-3">{{ "utils.new" | trans() }}</a>
                                </div>
                            </div>
                            {% include "user/datatable.html.twig" %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}